// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFuHc25QWh8-dacng9ZtrePrRPfcMVa0',
    appId: '1:556101373978:web:9864936ab48eddf00e81a3',
    messagingSenderId: '556101373978',
    projectId: 'chatmint-43c97',
    authDomain: 'chatmint-43c97.firebaseapp.com',
    storageBucket: 'chatmint-43c97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuWqXL-6_ZtrunGIBXofO6o3HB4VfboI',
    appId: '1:556101373978:android:b9513efe55c9a7a60e81a3',
    messagingSenderId: '556101373978',
    projectId: 'chatmint-43c97',
    storageBucket: 'chatmint-43c97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwjQHFgAYVTvPPsDcSCm9LUdjjQyVSh34',
    appId: '1:556101373978:ios:56d1cb6ffee9e6a70e81a3',
    messagingSenderId: '556101373978',
    projectId: 'chatmint-43c97',
    storageBucket: 'chatmint-43c97.firebasestorage.app',
    iosBundleId: 'com.example.chatmint',
  );
}
